[package]
name = "emdash-server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
axum = "0.8.9"
emdash-core = { version = "0.1.0", path = "../emdash-core" }
emdash-db = { version = "0.1.0", path = "../emdash-db" }
emdash-sandbox = { version = "0.1.0", path = "../emdash-sandbox" }
emdash-schema = { version = "0.1.0", path = "../emdash-schema" }
serde_json = "1.0.149"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
